# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np
random_array = np.random.random((3,3,3))
print(random_array)

[[[0.92955035 0.54878424 0.59160958]
  [0.77445836 0.31215232 0.40781346]
  [0.27152735 0.29899597 0.73179745]]

 [[0.49619923 0.3437167  0.87324623]
  [0.77626328 0.57107907 0.37493725]
  [0.74450096 0.92023166 0.69374993]]

 [[0.69390215 0.84785458 0.89708859]
  [0.7749551  0.25885752 0.51912143]
  [0.7105373  0.0669284  0.36061538]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
diagonal_arr = np.diag(1+np.arange(4), k = -1)
print (diagonal_arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
checkerboard = np.zeros ((9,9), dtype=int)
checkerboard[1::2, ::2]= 1 
checkerboard[::2, 1::2] = 1
print (checkerboard)

[[0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [6]:
x= np.random.random((3,3))
print("Original Array:\n")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("\nAfter normalization:\n")
print(x)

Original Array:

[[0.5661898  0.67196055 0.86116464]
 [0.3964394  0.70310149 0.31469154]
 [0.97487437 0.48355954 0.25982317]]

After normalization:

[[0.42845411 0.57637463 0.8409768 ]
 [0.19105797 0.61992528 0.07673349]
 [1.         0.31289559 0.        ]]


# 5.  How to find common values between two arrays?

In [7]:
array1 = np.array([0, 10, "tree", 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40,"tree"]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  ['0' '10' 'tree' '40' '60']
Array2:  [10, 30, 40, 'tree']
Common values between two arrays:
['10' '40' 'tree']


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [9]:
x = np.random.randint(0,2,6)
print("First array:",x)
y = np.random.randint(0,2,6)
print("Second array:",y)
array_equal = np.allclose(x, y)
if(array_equal == True):
    print("Two arrays are equal!")
else:
    print("Two arrays are not equal.")


First array: [1 1 1 0 1 1]
Second array: [0 1 1 0 0 0]
Two arrays are not equal.


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [10]:
x = np.random.random(10)
print("Original array:\n")
print(x)
x[x.argmax()] = 0
print("\nMaximum value replaced by 0:\n")
print(x)

Original array:

[0.52184641 0.23757531 0.72910995 0.12789028 0.57097226 0.26491897
 0.07102645 0.13615909 0.30208372 0.84833869]

Maximum value replaced by 0:

[0.52184641 0.23757531 0.72910995 0.12789028 0.57097226 0.26491897
 0.07102645 0.13615909 0.30208372 0.        ]


# 9. How to print all the values of an array?

In [11]:
#np.set_printoptions(threshold=np.nan)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [12]:
print("Original matrix:\n")
X = np.random.rand(3, 3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.89891565 0.17968694 0.57834374]
 [0.25261676 0.99140757 0.32796741]
 [0.41921803 0.54717926 0.06810724]]

Subtract the mean of each row of the said matrix:

[[ 0.3466002  -0.3726285   0.0260283 ]
 [-0.27138049  0.46741032 -0.19602983]
 [ 0.07438318  0.20234442 -0.2767276 ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [44]:
Z = np.ones(10)
print(Z) 
I =[1,3,5,7,9,1]
print(I) 
np.add.at(Z, I, 1)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1, 3, 5, 7, 9, 1]
[1. 3. 1. 2. 1. 2. 1. 2. 1. 2.]


# 12.How to get the diagonal of a dot product?

In [37]:
a1= [[1,2],[3,15]]
a2= [[5,6],[7,8]]
np.diag(np.dot(a1,a2))


array([ 19, 138])

# 13.How to find the most frequent value in an array?

In [27]:
x = np.random.randint(6, 10, 15)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[6 6 9 7 9 9 8 6 6 9 7 9 8 9 8]
Most frequent value in the above array:
9


# 14.How to get the n largest values of an array

In [18]:
x = np.arange(10)
print("Original array:\n")
print(x)
np.random.shuffle(x)
n = 1
print("\nlargest values of an array is ",x[np.argsort(x)[-n:]])

Original array:

[0 1 2 3 4 5 6 7 8 9]

largest values of an array is  [9]


# 15.How to create a record array from a regular array?

In [19]:
arra1 = np.array([("emly", 88.5, 90),
                 ("aana", 87, 99),
             ("Jose", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['emly' '88.5' '90']
 ['aana' '87' '99']
 ['Jose' '85.5' '91']]

Record array;
[(b'emly', 88.5, 90) (b'aana', 87. , 99) (b'Jose', 85.5, 91)]
