# SVM Classifier Algorithm

In [85]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import svm
from sklearn import neighbors

dataset = pd.read_csv('train.csv')
dataset = dataset.drop(['Name','Ticket','Cabin'],axis=1)
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  889 non-null    int64  
 1   Survived     889 non-null    int64  
 2   Pclass       889 non-null    int64  
 3   Sex          889 non-null    object 
 4   Age          889 non-null    float64
 5   SibSp        889 non-null    int64  
 6   Parch        889 non-null    int64  
 7   Fare         889 non-null    float64
 8   Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 62.6+ KB


In [86]:
dataset.drop_duplicates()
dataset.dropna()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
884          887         0       2    male  27.0      0      0  13.0000   
885          888         1       1  female  19.0      0      0  30.0000   
886          889         0       3  female  45.0      1      2  23.4500   
887          890         1       1    male  26.0      0      0  30.0000   
888          891         0       3    male  32.0      0      0   7.7500   

    Embarked  
0          S  
1          C  
2          S  
3          S  
4          S  
..       ...  
884        S  
885        S  
886        S  
887        C  
888        Q  

[889 rows x 9 columns]

In [87]:
le = preprocessing.LabelEncoder()
dataset['Sex'] = le.fit_transform(dataset['Sex'])
dataset['Embarked'] = le.fit_transform(dataset['Embarked'])
dataset['Age'] = np.where(dataset['Age'].isnull(),dataset['Age'].mean(),dataset['Age'])
dataset['Age'] = le.fit_transform(dataset['Age'])


In [88]:
def diagsum(mat): 
    sh = np.shape(mat)
    n = sh[0]
    principal = 0
    for i in range(0, n):  
        for j in range(0, n):  
            if (i == j): 
                principal += mat[i][j] 
    return principal

In [96]:
def svmclassifier(dependent_var):
    y = dataset[dependent_var]
    X = dataset.drop([dependent_var,'PassengerId'],axis=1)
    x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)
    n = y_test.size
    clf = svm.SVC(gamma=0.01,cache_size=100)
    clf.fit(x_train,y_train)
    y_pred = clf.predict(x_test)
    acc = accuracy_score(y_test,y_pred,normalize=True)
    c_mat = confusion_matrix(y_test,y_pred)
    print("Confusion Matrix:",dependent_var,"\n",c_mat)
    print("Here, Out of",n,"records, ",diagsum(c_mat),"records are correctly classified!\n and accuracy score is",round(acc*100),"%\n")


In [97]:
svmclassifier('Survived')

Confusion Matrix: Survived 
 [[91 14]
 [47 26]]
Here, Out of 178 records,  117 records are correctly classified!
 and accuracy score is 66.0 %



In [98]:
svmclassifier('Pclass')

Confusion Matrix: Pclass 
 [[41  6  0]
 [ 5 23  7]
 [ 3  8 85]]
Here, Out of 178 records,  149 records are correctly classified!
 and accuracy score is 84.0 %



In [99]:
svmclassifier('SibSp')

Confusion Matrix: SibSp 
 [[107  17   0   0   0   0   0]
 [ 21  17   0   0   2   0   0]
 [  3   1   0   0   0   0   0]
 [  0   4   1   0   1   0   0]
 [  0   0   0   0   1   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]]
Here, Out of 178 records,  128 records are correctly classified!
 and accuracy score is 72.0 %



In [100]:
svmclassifier('Parch')

Confusion Matrix: Parch 
 [[132   0   1   0   0]
 [ 18   5   0   0   0]
 [ 11   3   6   0   0]
 [  0   1   0   0   0]
 [  1   0   0   0   0]]
Here, Out of 178 records,  143 records are correctly classified!
 and accuracy score is 80.0 %



In [101]:
svmclassifier('Embarked')

Confusion Matrix: Embarked 
 [[  6   0  24]
 [  0   0  16]
 [  9   0 123]]
Here, Out of 178 records,  129 records are correctly classified!
 and accuracy score is 72.0 %



In [102]:
svmclassifier('Age')

Confusion Matrix: Age 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Here, Out of 178 records,  36 records are correctly classified!
 and accuracy score is 20.0 %



# svmclassifier('Survived') = 66.0 %
# svmclassifier('Pclass') = 84.0 %
# svmclassifier('SibSp') = 72.0 %
# svmclassifier('Parch') =  80.0 %
# svmclassifier('Embarked') = 72.0 %
# svmclassifier('Age') = 20.0%
# So far , Passenger class got the higher accuracy score 84.0 % in above combinations